{
    'name' : 'Indglobal Masters',
    'version' : '1.1',
	'author' : 'Indglobal digital private limited',
    'summary': 'Adding new Mastesr',
    'sequence': 1,
    'description': """Adding new masters""",
    'category' : 'base',
    'website': 'https://www.indglobal.com',
    'depends' : ['base','contacts'],
    'data': [
            'security/masters_security.xml',
            'views/vendor_groups_views.xml',
            'views/customer_groups_views.xml',
            'views/state_master_views.xml',
            'views/country_master_views.xml',
            'views/company_master_views.xml',
            'views/zone_master_views.xml',
            'views/branch_master_views.xml',
            'views/faq_questions_master.xml',
            'views/industry_master_views.xml',
            'views/fetchmail_views.xml',
            'security/ir.model.access.csv',
            ],
    'installable': True,
    'application': True,
    'auto_install': False,
    'license': 'OEEL-1',
}